/*
 * This source file was generated by the Gradle 'init' task
 */
package course.kristiyan;


import course.kristiyan.models.Shipment;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

public class App {
    public static int truckIdSeq = 0;
    public static Logger logger = Logger.getGlobal();
    public static List<Shipment> shipments;

    public static void main(String[] args) {
        shipments = new ArrayList<>();
    }
}
